version: "3.7"

services:
    flask:
        build: ./flask
        container_name: gdsc-ml-flask
        restart: always
        environment:
            - APP_NAME=manage
        expose:
            - 8888

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "0.0.0.0:80:80"